SUMMARY = "The Flutter engine."
DESCRIPTION = "The Flutter Engine is a portable runtime for hosting Flutter applications. \
It implements Flutter's core libraries, including animation and graphics, file and \
network I/O, accessibility support, plugin architecture, and a Dart runtime and compile \
toolchain. Most developers will interact with Flutter via the Flutter Framework, which \
provides a modern, reactive framework, and a rich set of platform, layout and foundation widgets."
HOMEPAGE = "https://flutter.dev"
LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://${THISDIR}/flutter-engine-bin/LICENSE;md5=537e0b52077bf0a616d0a0c8a79bc9d5"
